### ISSUE TITLE
Build fails with DMD 2.072.0

### ISSUE THREAD

**Issue by LightBender** [Pure-D/workspace-d#52]
The build fails with the following error:

../../.dub/packages/dub-1.1.0-beta.1/dub/source/dub/internal/sdlang/lexer.d(16,8): Error: module stream is in file 'std/stream.d' which cannot be read

I assume this is related to std.stream being removed from Phobos with 2.072.0.

**Comment by WebFreak001** [comment]
try `dub upgrade` before building and maybe also changing the dub dependency version in dub.json to 1.1.0 instead of 1.1.0-beta.1 and then running dub upgrade

**Comment by LightBender** [comment]
Yup, that worked. Thanks!

**Comment by dAnjou** [comment]
Not sure if it's okay to piggy-back here but the issue title still applies:

```
[max@xv15 ~]$ cd Downloads/workspace-d/
[max@xv15 workspace-d]$ dmd --version
DMD64 D Compiler v2.072.0
Copyright (c) 1999-2016 by Digital Mars written by Walter Bright
[max@xv15 workspace-d]$ dub --version
DUB version 1.0.0, built on Oct 31 2016
[max@xv15 workspace-d]$ sh install.sh 
Building package workspace-d:installer in /home/max/Downloads/workspace-d/installer/
Performing "debug" build using dmd for x86_64.
workspace-d:installer 2.8.0+commit.3.g2367725: building configuration "application"...
Linking...
Running ./installer/iworkspaced .
Welcome to the workspace-d installation guide.
Make sure, you have dub and git installed.

Which optional dependencies do you want to install?
[1] DCD - auto completion
[2] DScanner - code linting
[3] dfmt - code formatting
Enter a comma separated list of numbers
Selected [all]: 
Using existing git repository for workspace-d
Compiling...
$ dub upgrade
Upgrading project in /home/max/Downloads/workspace-d
$ dub build --build=release
Performing "release" build using dmd for x86_64.
dub 1.1.0: target for configuration "library" is up to date.
dunit 1.0.14: target for configuration "library" is up to date.
painlesstraits 0.2.0: target for configuration "library" is up to date.
painlessjson 1.3.8: target for configuration "library" is up to date.
workspace-d 2.8.0+commit.3.g2367725: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Successfully compiled workspace-d!
Cloning DCD into /tmp/workspaced-install-636151515648905581
$ git clone -q https://github.com/Hackerpilot/DCD.git DCD
Using ~master for building.
Compiling...
$ dub upgrade
Upgrading project in /tmp/workspaced-install-636151515648905581/DCD
$ dub build --build=release --config=client
Performing "release" build using dmd for x86_64.
emsi_containers 0.5.2: target for configuration "library" is up to date.
libdparse 0.7.0-beta.1: target for configuration "library" is up to date.
dsymbol 0.2.0-beta.1: target for configuration "library" is up to date.
msgpack-d 1.0.0-beta.5: target for configuration "library" is up to date.
dcd 0.9.0-alpha4+commit.37.ga36f64f: building configuration "client"...
Linking...
To force a rebuild of up-to-date targets, run again with --force.
$ dub build --build=release --config=server
Performing "release" build using dmd for x86_64.
emsi_containers 0.5.2: target for configuration "library" is up to date.
libdparse 0.7.0-beta.1: target for configuration "library" is up to date.
dsymbol 0.2.0-beta.1: target for configuration "library" is up to date.
msgpack-d 1.0.0-beta.5: target for configuration "library" is up to date.
dcd 0.9.0-alpha4+commit.37.ga36f64f: building configuration "server"...
../../../home/max/.dub/packages/dsymbol-0.2.0-beta.1/dsymbol/src/dsymbol/symbol.d(221,24): Deprecation: this.name.data.ptr cannot be used in @safe code, use &this.name.data[0] instead
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Successfully compiled DCD!
Cloning Dscanner into /tmp/workspaced-install-636151515648905581
$ git clone -q https://github.com/Hackerpilot/Dscanner.git Dscanner
Checking out v0.4.0-beta.3
$ git checkout -q v0.4.0-beta.3
Compiling...
$ git submodule update --init --recursive
Submodule 'containers' (https://github.com/economicmodeling/containers.git) registered for path 'containers'
Submodule 'dsymbol' (https://github.com/Hackerpilot/dsymbol.git) registered for path 'dsymbol'
Submodule 'inifiled' (https://github.com/burner/inifiled.git) registered for path 'inifiled'
Submodule 'libdparse' (https://github.com/Hackerpilot/libdparse.git) registered for path 'libdparse'
Cloning into 'containers'...
remote: Counting objects: 2144, done.
remote: Total 2144 (delta 0), reused 0 (delta 0), pack-reused 2144
Receiving objects: 100% (2144/2144), 660.34 KiB | 427.00 KiB/s, done.
Resolving deltas: 100% (1368/1368), done.
Checking connectivity... done.
Submodule path 'containers': checked out '528cae2880c0e5faa57d192621ad0533b0124b7b'
Cloning into 'dsymbol'...
remote: Counting objects: 663, done.
remote: Total 663 (delta 0), reused 0 (delta 0), pack-reused 663
Receiving objects: 100% (663/663), 225.43 KiB | 353.00 KiB/s, done.
Resolving deltas: 100% (309/309), done.
Checking connectivity... done.
Submodule path 'dsymbol': checked out '021df81dd8e23da2b76e8cb9c1b27a3c15efb5e7'
Cloning into 'inifiled'...
remote: Counting objects: 137, done.
remote: Total 137 (delta 0), reused 0 (delta 0), pack-reused 137
Receiving objects: 100% (137/137), 24.23 KiB | 0 bytes/s, done.
Resolving deltas: 100% (75/75), done.
Checking connectivity... done.
Submodule path 'inifiled': checked out 'e4f63f126ddddb3e496574fec0f76b24e61b1d51'
Cloning into 'libdparse'...
remote: Counting objects: 3139, done.
remote: Total 3139 (delta 0), reused 0 (delta 0), pack-reused 3138
Receiving objects: 100% (3139/3139), 1.44 MiB | 610.00 KiB/s, done.
Resolving deltas: 100% (2078/2078), done.
Checking connectivity... done.
Submodule path 'libdparse': checked out '1e24b41392c1363fc52a3d079debde965771be3e'
$ make
git log -1 --format="%H" > githash.txt
mkdir -p bin
dmd -w -inline -release -O -J. -odobj -version=StdLoggerDisableWarning -ofbin/dscanner  -Iinifiled/source -Isrc -Ilibdparse/src -Idsymbol/src -Icontainers/src containers/src/containers/unrolledlist.d containers/src/containers/ttree.d containers/src/containers/treemap.d containers/src/containers/slist.d containers/src/containers/simdset.d containers/src/containers/package.d containers/src/containers/openhashset.d containers/src/containers/internal/storage_type.d containers/src/containers/internal/node.d containers/src/containers/internal/mixins.d containers/src/containers/internal/hash.d containers/src/containers/internal/element_type.d containers/src/containers/internal/backwards.d containers/src/containers/immutablehashset.d containers/src/containers/hashset.d containers/src/containers/hashmap.d containers/src/containers/dynamicarray.d containers/src/containers/cyclicbuffer.d dsymbol/src/dsymbol/type_lookup.d dsymbol/src/dsymbol/symbol.d dsymbol/src/dsymbol/string_interning.d dsymbol/src/dsymbol/semantic.d dsymbol/src/dsymbol/scope_.d dsymbol/src/dsymbol/modulecache.d dsymbol/src/dsymbol/import_.d dsymbol/src/dsymbol/deferred.d dsymbol/src/dsymbol/conversion/second.d dsymbol/src/dsymbol/conversion/package.d dsymbol/src/dsymbol/conversion/first.d dsymbol/src/dsymbol/cache_entry.d dsymbol/src/dsymbol/builtin/symbols.d dsymbol/src/dsymbol/builtin/names.d inifiled/source/inifiled.d libdparse/src/std/experimental/lexer.d libdparse/src/dparse/stack_buffer.d libdparse/src/dparse/rollback_allocator.d libdparse/src/dparse/parser.d libdparse/src/dparse/lexer.d libdparse/src/dparse/formatter.d libdparse/src/dparse/entities.d libdparse/src/dparse/ast.d src/symbol_finder.d src/stats.d src/readers.d src/outliner.d src/main.d src/imports.d src/highlighter.d src/etags.d src/dscanner_version.d src/ctags.d src/astprinter.d src/analysis/useless_assert.d src/analysis/unused_label.d src/analysis/unused.d src/analysis/unmodified.d src/analysis/undocumented.d src/analysis/style.d src/analysis/stats_collector.d src/analysis/static_if_else.d src/analysis/run.d src/analysis/redundant_parens.d src/analysis/range.d src/analysis/pokemon.d src/analysis/package.d src/analysis/opequals_without_tohash.d src/analysis/objectconst.d src/analysis/numbers.d src/analysis/mismatched_args.d src/analysis/logic_precedence.d src/analysis/local_imports.d src/analysis/line_length.d src/analysis/length_subtraction.d src/analysis/lambda_return_check.d src/analysis/label_var_same_name_check.d src/analysis/incorrect_infinite_range.d src/analysis/ifelsesame.d src/analysis/if_statements.d src/analysis/helpers.d src/analysis/function_attributes.d src/analysis/fish.d src/analysis/enumarrayliteral.d src/analysis/duplicate_attribute.d src/analysis/del.d src/analysis/constructors.d src/analysis/config.d src/analysis/comma_expression.d src/analysis/builtin_property_names.d src/analysis/base.d src/analysis/auto_ref_assignment.d src/analysis/auto_function.d src/analysis/asm_style.d src/analysis/alias_syntax_check.d
dsymbol/src/dsymbol/symbol.d(208): Deprecation: this.name.data.ptr cannot be used in @safe code, use &this.name.data[0] instead
dsymbol/src/dsymbol/symbol.d(208): Deprecation: other.name.data.ptr cannot be used in @safe code, use &other.name.data[0] instead
dsymbol/src/dsymbol/symbol.d(209): Deprecation: this.name.data.ptr cannot be used in @safe code, use &this.name.data[0] instead
dsymbol/src/dsymbol/symbol.d(209): Deprecation: other.name.data.ptr cannot be used in @safe code, use &other.name.data[0] instead
dsymbol/src/dsymbol/symbol.d(216): Deprecation: other.name.data.ptr cannot be used in @safe code, use &other.name.data[0] instead
dsymbol/src/dsymbol/symbol.d(216): Deprecation: this.name.data.ptr cannot be used in @safe code, use &this.name.data[0] instead
dsymbol/src/dsymbol/symbol.d(221): Deprecation: this.name.data.ptr cannot be used in @safe code, use &this.name.data[0] instead
rm -f bin/dscanner.o
Successfully compiled Dscanner!
Cloning dfmt into /tmp/workspaced-install-636151515648905581
$ git clone -q https://github.com/Hackerpilot/dfmt.git dfmt
Checking out v0.5.0-beta3
$ git checkout -q v0.5.0-beta3
Compiling...
$ dub upgrade
Upgrading project in /tmp/workspaced-install-636151515648905581/dfmt
$ dub build --build=release
Performing "release" build using dmd for x86_64.
experimental_allocator 2.70.0-b1: building configuration "library"...
../../../home/max/.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/package.d(322,13): Error: std.experimental.allocator.common.Ternary at ../../../home/max/.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/common.d(14,1) conflicts with std.typecons.Ternary at /usr/include/dmd/phobos/std/typecons.d(7427,1)
../../../home/max/.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/package.d(328,13): Error: std.experimental.allocator.common.Ternary at ../../../home/max/.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/common.d(14,1) conflicts with std.typecons.Ternary at /usr/include/dmd/phobos/std/typecons.d(7427,1)
../../../home/max/.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/package.d(348,13): Error: std.experimental.allocator.common.Ternary at ../../../home/max/.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/common.d(14,1) conflicts with std.typecons.Ternary at /usr/include/dmd/phobos/std/typecons.d(7427,1)
dmd failed with exit code 1.
Error while compiling dfmt.
Program exited with code 1
[max@xv15 workspace-d]$ 
```

**Comment by WebFreak001** [comment]
Well it fails at installing dfmt. Does manually compiling dfmt work?

**Comment by dAnjou** [comment]
The whole thing works with DMD64 D Compiler v2.071.2.
