### ISSUE TITLE
OSX dub build fails with getUDAs! template not defined

### ISSUE THREAD

**Issue by AndrewSChapman** [Pure-D/workspace-d#7]
Hi there, I've tried building workspace-d (the latest version and a few historical versions as well) on OSX El Capitan, however when I run dub build I get:

source/app.d(205,30): Error: template instance getUDAs!(symbol, Arguments) template 'getUDAs' is not defined
source/app.d(224,84): Error: template instance getUDAs!(symbol, component) template 'getUDAs' is not defined
source/app.d(234,56): Error: template instance getUDAs!(symbol, component) template 'getUDAs' is not defined
source/app.d(237,95): Error: template instance getUDAs!(symbol, component) template 'getUDAs' is not defined
source/app.d(205,30): Error: template instance getUDAs!(symbol, Arguments) template 'getUDAs' is not defined
source/app.d(224,84): Error: template instance getUDAs!(symbol, component) template 'getUDAs' is not defined
source/app.d(248,56): Error: template instance getUDAs!(symbol, component) template 'getUDAs' is not defined
source/app.d(251,95): Error: template instance getUDAs!(symbol, component) template 'getUDAs' is not defined
source/app.d(205,30): Error: template instance getUDAs!(symbol, Arguments) template 'getUDAs' is not defined
source/app.d(224,84): Error: template instance getUDAs!(symbol, component) template 'getUDAs' is not defined
source/app.d(205,30): Error: template instance getUDAs!(symbol, Arguments) template 'getUDAs' is not defined
source/app.d(224,84): Error: template instance getUDAs!(symbol, component) template 'getUDAs' is not defined
source/app.d(205,30): Error: template instance getUDAs!(symbol, Arguments) template 'getUDAs' is not defined
source/app.d(224,84): Error: template instance getUDAs!(symbol, component) template 'getUDAs' is not defined
source/app.d(205,30): Error: template instance getUDAs!(symbol, Arguments) template 'getUDAs' is not defined
source/app.d(224,84): Error: template instance getUDAs!(symbol, component) template 'getUDAs' is not defined
source/app.d(205,30): Error: template instance getUDAs!(symbol, Arguments) template 'getUDAs' is not defined
source/app.d(224,84): Error: template instance getUDAs!(symbol, component) template 'getUDAs' is not defined
source/app.d(205,30): Error: template instance getUDAs!(symbol, Arguments) template 'getUDAs' is not defined
source/app.d(224,84): Error: template instance getUDAs!(symbol, component) template 'getUDAs' is not defined

dmd compiler version is:
DMD64 D Compiler v2.068.2
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright

Any ideas how to resolve?  Keen to try this in Visual Studio Code.
Cheers,
Andrew.

**Comment by WebFreak001** [comment]
This is weird we also had this issue with windows now. Does it work with dmd 2.069.2?

**Comment by AndrewSChapman** [comment]
Actually, yes it does :-)  Thanks, working on the latest DMD compiler.
